### ISSUE TITLE
A rest parameter must be of an array type (react-redux)

### ISSUE THREAD

**Issue by nemethmik** [xyberzues/react-material-ui-typescript#1]
Hi,
After I have run **npm update**, the project doesn't compile because of this error:
ts-loader: Using typescript@2.9.2 and C:\Users\nemet\tiva11\react-material-ui-typescript\tsconfig.prod.json
Failed to compile.
C:/Users/nemet/tiva11/react-material-ui-typescript/node_modules/@types/react-redux/index.d.ts
(116,29): A rest parameter must be of an array type.

Before updating the packages with **npm update** , the project compiled and worked fine.
Thank you and all the best,
Miklos

**Comment by manuga93** [comment]
+1

**Comment by seanngpack** [comment]
same

**Comment by seanngpack** [comment]
Same issue, anyone figure it out?

**Comment by goemen** [comment]
Sorry for the wait, try `npm i -D typescript@3.2.2`

**Comment by goemen** [comment]
@seanngpack you can pull from master, I think that I have resolved the issue
